language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - main

deploy:
  provider: heroku
  app: ministeam
  api_key:
    secure: FKTvJee5KNzGizTyNdouyy/bkgHP5QaInAROvHs9Rd50POadBAGT7PlLurUstK8oN2KHkMbZqSjOUL95MU/HsfdMwvDPIc/J8hxs0xZ/MctzEbidnDdXMGwFiWaNqCiHR8BsbF7tp7gZCoy5QQX1/FB4djV1d+o1murh9P4pS25u1aUm722gam+Qz0/darUdwL34lYYPACX4Y4I4b1Yy/gSEi3TXVjkmk9Ge/OYO9/V/4EyGw1WibKAruBLW3Mi9YsVKmmw4mL3P1AZMkNAkre8BHfMrecXbmciXtYWAxDqq7hHv9rl3N/zRhXuJZIAfDgzS577Kh6Vofbpz1yOL++s43mcizd5qo6/V1L2+5UaSHSryWAaxKCyZwlKYOGG+fNtQEiNqiyw+ZPt6MTb0DZtlXXxnVGNwk8ZH9fjMVLWfm8RSvLTOsEH2uOECfSYVw9DZ3B0lTqTGOqY1I7Vbm4EuNE03UkYyCIUNa47NmejTB1owZalPzJQ9a1IapG7zuKTQNtY86mdRNfYeSJ/ojPBSxc2Pk4uhjAcPy96QOc+CKd5qwH1GOcLzl3GMLQa/rk1I8zpAhO3ovFBLP8W9gipveM/QRWGxzMONmAzidvrloz56KAaXDuvmgPffWBW9cEm63Ajvsa2KuQKKitbUy1PFE8XZDGrG4g5tQeuxEnk=